version: "3"

services:
  postgres:
    image: "postgres"
    volumes:
      - "postgres:/var/lib/postgresql/data"

  redis:
    image: "redis:5.0.0-alpine"
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - "redis:/var/lib/redis/data"

  app:
    depends_on:
      - "postgres"
      - "redis"
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
      - "gems:/gems"

  job:
    depends_on:
      - "postgres"
      - "redis"
      - "app"
      - "elasticsearch"
    build: .
    command: bash start_jobs.sh
    volumes:
      - ".:/app"
      - "gems:/gems"
    environment:
      ELASTICSEARCH_URL: elasticsearch:9200

  elasticsearch:
    image: "elasticsearch:5.6.13-alpine"
    ports:
      - "9200:9200"
    volumes:
      - "elastic:/usr/share/elasticsearch/data"
    environment:
      - Des.network.host=0.0.0.0

volumes:
  redis:
  postgres:
  gems:
  elastic: